sonar.organization=dev-1603
sonar.projectKey=dev-1603_celestial-ui-design-system

sonar.sources=packages,tooling
sonar.exclusions=**/dist/**,**/node_modules/**,**/.turbo/**,**/coverage/**,**/generated/**,**/*.test.ts
sonar.tests=packages,tooling
sonar.test.inclusions=**/*.test.ts
