import { FlatTokenMap } from './resolve';

function formatVarName(path: string): string {
  return `--cui-${path.replace(/\./g, '-')}`;
}

export function generateCSS(resolvedTokens: FlatTokenMap): string {
  let css = '/* Auto-generated by @celestial-ui/tokens */\n\n:root {\n';

  for (const [key, token] of Object.entries(resolvedTokens)) {
    if (typeof token.$value === 'object' && !Array.isArray(token.$value) && token.$value !== null) {
      // Handle composite tokens (e.g. typography, border)
      for (const [subKey, subValue] of Object.entries(token.$value)) {
        css += `  ${formatVarName(`${key}-${subKey}`)}: ${subValue};\n`;
      }
    } else if (Array.isArray(token.$value)) {
      // Handle array values like shadows
      if (token.$type === 'shadow') {
        const shadowStr = token.$value
          .map(
            (s: any) =>
              `${s.inset ? 'inset ' : ''}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`,
          )
          .join(', ');
        css += `  ${formatVarName(key)}: ${shadowStr};\n`;
      }
    } else {
      // Standard primitive
      css += `  ${formatVarName(key)}: ${token.$value};\n`;
    }
  }

  css += '}\n';
  return css;
}

export function generateShadcnMapping(resolvedTokens: FlatTokenMap): string {
  let css = '/* Auto-generated shadcn compatibility mapping */\n\n:root {\n';

  // Mapping shadcn names to standard celestial semantics
  const shadcnMap: Record<string, string> = {
    '--background': 'surface.canvas',
    '--foreground': 'text.primary',
    '--card': 'surface.elevated',
    '--card-foreground': 'text.primary', // Approximation, using primary text
    '--popover': 'surface.subtle',
    '--popover-foreground': 'text.primary',
    '--primary': 'action.primary.background',
    '--primary-foreground': 'action.primary.text',
    '--secondary': 'surface.subtle',
    '--secondary-foreground': 'text.secondary',
    '--muted': 'surface.subtle',
    '--muted-foreground': 'text.muted',
    '--accent': 'surface.elevated',
    '--accent-foreground': 'text.primary',
    '--destructive': 'status.error',
    '--destructive-foreground': 'text.inverse',
    '--border': 'border.default',
    '--input': 'border.default',
    '--ring': 'focus.color',
    '--radius': 'radius.md',
  };

  for (const [shadcnKey, celestialKey] of Object.entries(shadcnMap)) {
    if (resolvedTokens[celestialKey]) {
      css += `  ${shadcnKey}: var(${formatVarName(celestialKey)});\n`;
    }
  }

  css += '}\n';
  return css;
}

export function generateTailwindPreset(resolvedTokens: FlatTokenMap): string {
  let js = "/** @type {import('tailwindcss').Config} */\n";
  js += 'module.exports = {\n  theme: {\n    extend: {\n';

  const map: Record<string, Record<string, string>> = {
    colors: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    lineHeight: {},
    letterSpacing: {},
    zIndex: {},
    transitionDuration: {},
    transitionTimingFunction: {},
  };

  for (const [key, token] of Object.entries(resolvedTokens)) {
    const value = `var(${formatVarName(key)})`;
    const tailwindKey = key.split('.').slice(1).join('-'); // e.g., "color.blue.500" -> "blue-500"

    if (token.$type === 'color') map.colors[key.replace('color.', '').replace(/\./g, '-')] = value;
    else if (token.$type === 'dimension' && key.startsWith('space.'))
      map.spacing[key.replace('space.', '')] = value;
    else if (token.$type === 'dimension' && key.startsWith('size.'))
      map.spacing[key.replace('size.', '')] = value; // Tailwind mixes sizing in spacing, or width/height
    else if (token.$type === 'dimension' && key.startsWith('radius.'))
      map.borderRadius[key.replace('radius.', '')] = value;
    else if (token.$type === 'shadow') map.boxShadow[key.replace('shadow.', '')] = value;
    else if (token.$type === 'fontFamily') map.fontFamily[key.replace('fontFamily.', '')] = value;
    else if (token.$type === 'dimension' && key.startsWith('fontSize.'))
      map.fontSize[key.replace('fontSize.', '')] = value;
    else if (token.$type === 'fontWeight') map.fontWeight[key.replace('fontWeight.', '')] = value;
    else if (token.$type === 'number' && key.startsWith('lineHeight.'))
      map.lineHeight[key.replace('lineHeight.', '')] = value;
    else if (token.$type === 'dimension' && key.startsWith('letterSpacing.'))
      map.letterSpacing[key.replace('letterSpacing.', '')] = value;
    else if (token.$type === 'number' && key.startsWith('z.'))
      map.zIndex[key.replace('z.', '')] = value;
    else if (token.$type === 'duration')
      map.transitionDuration[key.replace('motion.duration.', '')] = value;
    else if (token.$type === 'cubicBezier')
      map.transitionTimingFunction[key.replace('motion.easing.', '')] = value;
  }

  for (const [twCategory, values] of Object.entries(map)) {
    if (Object.keys(values).length > 0) {
      js += `      ${twCategory}: ${JSON.stringify(values, null, 8).replace(/\n/g, '\n      ')},\n`;
    }
  }

  js += '    }\n  }\n};\n';
  return js;
}

export function generateTS(resolvedTokens: FlatTokenMap): string {
  let ts = '/* Auto-generated by @celestial-ui/tokens */\n\n';
  ts += 'export const tokens = {\n';

  for (const [key, token] of Object.entries(resolvedTokens)) {
    if (typeof token.$value === 'object' && !Array.isArray(token.$value) && token.$value !== null) {
      ts += `  "${key}": ${JSON.stringify(token.$value)},\n`;
    } else if (Array.isArray(token.$value)) {
      ts += `  "${key}": ${JSON.stringify(token.$value)},\n`;
    } else {
      ts += `  "${key}": "${token.$value}",\n`;
    }
  }

  ts += '} as const;\n\n';

  ts += 'export const cssVars = {\n';
  for (const [key, token] of Object.entries(resolvedTokens)) {
    if (typeof token.$value === 'object' && !Array.isArray(token.$value) && token.$value !== null) {
      for (const [subKey] of Object.entries(token.$value)) {
        ts += `  "${key}-${subKey}": "var(${formatVarName(`${key}-${subKey}`)})",\n`;
      }
    } else {
      ts += `  "${key}": "var(${formatVarName(key)})",\n`;
    }
  }
  ts += '} as const;\n';

  return ts;
}
