import type { FlatTokenMap } from './resolve';
import type { ShadowValue, Token } from './types';

function formatVarName(path: string): string {
  return `--cui-${path.replaceAll('.', '-')}`;
}

function formatShadowValue(shadows: ShadowValue[]): string {
  return shadows
    .map((s) => {
      const inset = s.inset ? 'inset ' : '';
      return `${inset}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`;
    })
    .join(', ');
}

function appendCssCustomProperty(lines: string[], name: string, value: string | number): void {
  lines.push(`  ${name}: ${value};`);
}

export function generateCSS(resolvedTokens: FlatTokenMap): string {
  const lines: string[] = ['/* Auto-generated by @celestial-ui/tokens */', '', ':root {'];

  for (const [key, token] of Object.entries(resolvedTokens)) {
    if (typeof token.$value === 'object' && !Array.isArray(token.$value) && token.$value !== null) {
      for (const [subKey, subValue] of Object.entries(token.$value)) {
        appendCssCustomProperty(lines, formatVarName(`${key}-${subKey}`), String(subValue));
      }
    } else if (Array.isArray(token.$value) && token.$type === 'shadow') {
      appendCssCustomProperty(lines, formatVarName(key), formatShadowValue(token.$value));
    } else if (!Array.isArray(token.$value)) {
      appendCssCustomProperty(lines, formatVarName(key), token.$value);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

export function generateShadcnMapping(resolvedTokens: FlatTokenMap): string {
  const lines: string[] = ['/* Auto-generated shadcn compatibility mapping */', '', ':root {'];
  const shadcnMap: Record<string, string> = {
    '--background': 'surface.canvas',
    '--foreground': 'text.primary',
    '--card': 'surface.elevated',
    '--card-foreground': 'text.primary',
    '--popover': 'surface.subtle',
    '--popover-foreground': 'text.primary',
    '--primary': 'action.primary.background',
    '--primary-foreground': 'action.primary.text',
    '--secondary': 'surface.subtle',
    '--secondary-foreground': 'text.secondary',
    '--muted': 'surface.subtle',
    '--muted-foreground': 'text.muted',
    '--accent': 'surface.elevated',
    '--accent-foreground': 'text.primary',
    '--destructive': 'status.error',
    '--destructive-foreground': 'text.inverse',
    '--border': 'border.default',
    '--input': 'border.default',
    '--ring': 'focus.color',
    '--radius': 'radius.md',
  };

  for (const [shadcnKey, celestialKey] of Object.entries(shadcnMap)) {
    if (resolvedTokens[celestialKey]) {
      appendCssCustomProperty(lines, shadcnKey, `var(${formatVarName(celestialKey)})`);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

type TailwindExtendMap = Record<string, Record<string, string>>;

function stripPrefix(key: string, prefix: string): string {
  return key.startsWith(prefix) ? key.slice(prefix.length) : key;
}

function assignTailwindValue(
  map: TailwindExtendMap,
  key: string,
  token: Token,
  value: string,
): void {
  switch (token.$type) {
    case 'color':
      map.colors[key.replace('color.', '').replaceAll('.', '-')] = value;
      return;
    case 'shadow':
      map.boxShadow[stripPrefix(key, 'shadow.')] = value;
      return;
    case 'fontFamily':
      map.fontFamily[stripPrefix(key, 'fontFamily.')] = value;
      return;
    case 'fontWeight':
      map.fontWeight[stripPrefix(key, 'fontWeight.')] = value;
      return;
    case 'duration':
      map.transitionDuration[stripPrefix(key, 'motion.duration.')] = value;
      return;
    case 'cubicBezier':
      map.transitionTimingFunction[stripPrefix(key, 'motion.easing.')] = value;
      return;
    case 'dimension':
      assignTailwindDimension(map, key, value);
      return;
    case 'number':
      assignTailwindNumber(map, key, value);
      return;
    default:
      return;
  }
}

function assignTailwindDimension(map: TailwindExtendMap, key: string, value: string): void {
  if (key.startsWith('space.')) {
    map.spacing[stripPrefix(key, 'space.')] = value;
    return;
  }
  if (key.startsWith('size.')) {
    map.spacing[stripPrefix(key, 'size.')] = value;
    return;
  }
  if (key.startsWith('radius.')) {
    map.borderRadius[stripPrefix(key, 'radius.')] = value;
    return;
  }
  if (key.startsWith('fontSize.')) {
    map.fontSize[stripPrefix(key, 'fontSize.')] = value;
    return;
  }
  if (key.startsWith('letterSpacing.')) {
    map.letterSpacing[stripPrefix(key, 'letterSpacing.')] = value;
  }
}

function assignTailwindNumber(map: TailwindExtendMap, key: string, value: string): void {
  if (key.startsWith('lineHeight.')) {
    map.lineHeight[stripPrefix(key, 'lineHeight.')] = value;
    return;
  }
  if (key.startsWith('z.')) {
    map.zIndex[stripPrefix(key, 'z.')] = value;
  }
}

function emptyTailwindMap(): TailwindExtendMap {
  return {
    colors: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    lineHeight: {},
    letterSpacing: {},
    zIndex: {},
    transitionDuration: {},
    transitionTimingFunction: {},
  };
}

export function generateTailwindPreset(resolvedTokens: FlatTokenMap): string {
  const lines = [
    "/** @type {import('tailwindcss').Config} */",
    'module.exports = {',
    '  theme: {',
    '    extend: {',
  ];

  const map = emptyTailwindMap();

  for (const [key, token] of Object.entries(resolvedTokens)) {
    assignTailwindValue(map, key, token, `var(${formatVarName(key)})`);
  }

  for (const [twCategory, values] of Object.entries(map)) {
    if (Object.keys(values).length > 0) {
      const serialized = JSON.stringify(values, null, 8).replaceAll('\n', '\n      ');
      lines.push(`      ${twCategory}: ${serialized},`);
    }
  }

  lines.push('    }', '  }', '};', '');
  return lines.join('\n');
}

function appendTsTokenEntry(lines: string[], key: string, token: Token): void {
  if (typeof token.$value === 'object' && token.$value !== null) {
    lines.push(`  "${key}": ${JSON.stringify(token.$value)},`);
    return;
  }
  lines.push(`  "${key}": "${token.$value}",`);
}

function appendTsCssVarEntries(lines: string[], key: string, token: Token): void {
  if (typeof token.$value === 'object' && !Array.isArray(token.$value) && token.$value !== null) {
    for (const [subKey] of Object.entries(token.$value)) {
      const varName = formatVarName(`${key}-${subKey}`);
      lines.push(`  "${key}-${subKey}": "var(${varName})",`);
    }
    return;
  }
  const varName = formatVarName(key);
  lines.push(`  "${key}": "var(${varName})",`);
}

export function generateTS(resolvedTokens: FlatTokenMap): string {
  const tokenLines = [
    '/* Auto-generated by @celestial-ui/tokens */',
    '',
    'export const tokens = {',
  ];
  for (const [key, token] of Object.entries(resolvedTokens)) {
    appendTsTokenEntry(tokenLines, key, token);
  }
  tokenLines.push('} as const;', '', 'export const cssVars = {');
  for (const [key, token] of Object.entries(resolvedTokens)) {
    appendTsCssVarEntries(tokenLines, key, token);
  }
  tokenLines.push('} as const;', '');
  return tokenLines.join('\n');
}
