#!/usr/bin/env node
/**
 * Embeds canonical token JSON so getCanonicalTokenSources() has no Node I/O
 * on the module graph (browser DCE + Bun/Node/SSR).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const tokensRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(tokensRoot, 'data');
const outDir = path.join(tokensRoot, 'src/generated');
const outFile = path.join(outDir, 'canonical-sources.ts');

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(dataDir, relativePath), 'utf8'));
}

const sources = {
  primitives: readJson('primitives.json'),
  foundations: readJson('foundations.json'),
  components: readJson('components.json'),
  light: readJson('themes/celestial/light.json'),
  dark: readJson('themes/celestial/dark.json'),
};

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  outFile,
  '/* GENERATED by scripts/embed-catalog.mjs — do not edit. */\n' +
    "import type { TokenConfig } from '../types';\n\n" +
    `export const CANONICAL_PRIMITIVES: TokenConfig = ${JSON.stringify(sources.primitives)} as TokenConfig;\n` +
    `export const CANONICAL_FOUNDATIONS: TokenConfig = ${JSON.stringify(sources.foundations)} as TokenConfig;\n` +
    `export const CANONICAL_COMPONENTS: TokenConfig = ${JSON.stringify(sources.components)} as TokenConfig;\n` +
    `export const CANONICAL_LIGHT: TokenConfig = ${JSON.stringify(sources.light)} as TokenConfig;\n` +
    `export const CANONICAL_DARK: TokenConfig = ${JSON.stringify(sources.dark)} as TokenConfig;\n`,
);
console.log(`wrote ${path.relative(tokensRoot, outFile)}`);
